environment: development
environmentCode:
name: adp-demo-03
namespace: adp
workstream: adp
image: adp-demo-03

labels:
  component: web

appInsights:
  connectionString:

containerConfigMap:
  name: adp-demo-03-config-map

containerSecret:
  name: adp-demo-03-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
