{{- include "adp-helm-library.deployment" (list . "adp-demo-03.deployment") -}}
{{- define "adp-demo-03.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "adp-demo-03.container") }}
{{- end -}}
